sudo: required
language: rust
dist: xenial

cache: cargo

addons:
  apt:
    packages:
      - cmake
      - g++
      - pkg-config
      - jq
      - libssl-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo install cargo-travis
    cargo install cargo-kcov
  fi
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    rustup component add clippy
  fi

script:
  - |
      cargo update &&
      cargo build &&
      cargo test &&
      cargo doc

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo clippy -- -D warnings
  fi
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo doc-upload --token ${GITHUB_TOKEN}
    cargo kcov --print-install-kcov-sh | sh
    cargo kcov --coveralls -v -- \
        --verify \
        --exclude-pattern=/home/elshize/.cargo,/usr/include,tests.rs,main.rs
  fi
