sudo: required
language: rust
dist: xenial

cache: cargo

addons:
  apt:
    packages:
      - cmake
      - libssl-dev

rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
    cargo install cargo-travis
  fi

script:
  - |
      cargo update &&
      cargo build &&
      cargo test &&
      cargo doc

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo doc-upload --token ${GITHUB_TOKEN}
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
