[package]
name = "standard-benchmark"
version = "0.1.0"
authors = ["Michal Siedlaczek <michal.siedlaczek@nyu.edu>"]
edition = "2018"

[lib]
name = "stdbench"

[dependencies]
experiment = { git = "https://github.com/elshize/experiment-rs", branch="master" }
clap = "2.24"
json = "0.11"
git2 = "0.8"
log = "0.4"
stderrlog = "0.4"
yaml-rust = "0.4"
glob = "0.3"
tempdir = "0.3"
downcast-rs = "1.0"
boolinator = "2.4.0"
